sudo: required
services: docker
language: node_js

env:
    global:
        - DOCKER_COMPOSE_VERSION=1.8.1

script:
    - npm install travis-ci
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/trigger-build.js
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/push.sh
    - chmod +x push.sh
    - ./pipe_build_up_test.sh ${DOCKER_COMPOSE_VERSION}
    - ./push.sh
    - node trigger-build.js cyber-dojo/system-tests
