sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_COMPOSE_VERSION=1.8.1

script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/push.sh
    - chmod +x push.sh
    - ./pipe_build_up_test.sh ${DOCKER_COMPOSE_VERSION}
    - ./push.sh
