
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Note: Dependencies between nginx and web are reflected in the
# nginx.conf file
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

version: '2'

volumes:
  languages:
    external:
      name: ${CYBER_DOJO_START_POINT_LANGUAGES}
  exercises:
    external:
      name: ${CYBER_DOJO_START_POINT_EXERCISES}
  custom:
    external:
      name: ${CYBER_DOJO_START_POINT_CUSTOM}
  grafana_data: {}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

services:

  nginx:
    user: root
    image: cyberdojo/nginx
    container_name: cyber-dojo-nginx
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure
    depends_on:
      - web
    ports: [ "80:80" ]

  web:
    user: root
    image: cyberdojo/web
    container_name: cyber-dojo-web
    environment:
      - CYBER_DOJO_HOME
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    depends_on:
      - puller
      - runner
      - storer
      - differ
      - zipper
    volumes:
      - languages:${CYBER_DOJO_HOME}/start_points/languages:ro
      - exercises:${CYBER_DOJO_HOME}/start_points/exercises:ro
      - custom:${CYBER_DOJO_HOME}/start_points/custom:ro

  puller:
    user: root
    image: cyberdojo/puller
    container_name: cyber-dojo-puller
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner:
    user: root
    image: cyberdojo/runner
    container_name: cyber-dojo-runner
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  storer:
    user: cyber-dojo
    image: cyberdojo/storer
    container_name: cyber-dojo-storer
    read_only: true
    environment:
      - CYBER_DOJO_KATAS_ROOT
    volumes_from:
      - container:${CYBER_DOJO_KATAS_DATA_CONTAINER}:rw
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure

  differ:
    user: nobody
    image: cyberdojo/differ
    container_name: cyber-dojo-differ
    read_only: true
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: on-failure

  collector:
    user: root
    image: cyberdojo/collector
    container_name: cyber-dojo-collector
    cpu_shares: 32
    mem_limit: 1G
    memswap_limit: 1G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zipper:
    user: zipper
    image: cyberdojo/zipper
    container_name: cyber-dojo-zipper
    cpu_shares: 16
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure
    depends_on:
      - storer

  # - - - - - - - - - - - - - - - - - - - - - - -

  prometheus:
    image: cyberdojo/prometheus
    container_name: cyber-dojo-prometheus

  grafana:
    image: cyberdojo/grafana
    container_name: cyber-dojo-grafana
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    env_file:
      - /app/grafana.env
    ports:
      - '3000:3000'
