
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# I'd like to set cpu/memory/swap limits on the test-run containers
# and the app containers independently.
# This appears to be impossible so I have to try to get some kind
# of compromise; I don't want to limit the web-server but I do want
# to limit the test-containers. However if the limits are too low
# the web server container is unable to [docker pull] images on-demand
# in the setup pages.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Note: Dependencies between nginx and web are reflected in the
# nginx.conf file
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

version: '2'

volumes:
  languages:
    external:
      name: ${CYBER_DOJO_START_POINT_LANGUAGES}
  exercises:
    external:
      name: ${CYBER_DOJO_START_POINT_EXERCISES}
  custom:
    external:
      name: ${CYBER_DOJO_START_POINT_CUSTOM}

services:
  nginx:
    user: root
    image: cyberdojo/nginx
    container_name: cyber-dojo-nginx
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure
    ports: [ "80:80" ]

  web:
    user: root
    image: cyberdojo/web
    container_name: cyber-dojo-web
    environment: [ CYBER_DOJO_HOME ]
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    volumes:
      - languages:${CYBER_DOJO_HOME}/start_points/languages:ro
      - exercises:${CYBER_DOJO_HOME}/start_points/exercises:ro
      - custom:${CYBER_DOJO_HOME}/start_points/custom:ro

  puller:
    user: root
    image: cyberdojo/puller
    container_name: cyber-dojo-puller
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner:
    user: root
    image: cyberdojo/runner
    container_name: cyber-dojo-runner
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  storer:
    user: cyber-dojo
    image: cyberdojo/storer
    container_name: cyber-dojo-storer
    read_only: true
    environment: [ CYBER_DOJO_KATAS_ROOT=/usr/src/cyber-dojo/katas ]
    volumes_from:
      - container:${CYBER_DOJO_KATAS_DATA_CONTAINER}:rw
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure

  differ:
    user: nobody
    image: cyberdojo/differ
    container_name: cyber-dojo-differ
    read_only: true
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: on-failure

  collector:
    user: root
    image: cyberdojo/collector
    container_name: cyber-dojo-collector
    cpu_shares: 32
    mem_limit: 1G
    memswap_limit: 1G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
